<?php
require('../fpdf/fpdf.php');
include("../config.php");

if (!isset($_GET['receipt_no'])) {
    die("Receipt number missing!");
}

$receipt_no = $_GET['receipt_no'];

// Fetch payment + student info
$sql = "SELECT p.*, s.name AS student_name, s.grade, s.class_id
        FROM payments p
        JOIN students s ON p.student_id = s.student_id
        WHERE p.receipt_no = '$receipt_no'";

$result = $conn->query($sql);
if ($result->num_rows == 0) {
    die("Invalid receipt number");
}
$row = $result->fetch_assoc();

// Create PDF instance
$pdf = new FPDF();
$pdf->AddPage();
$pdf->SetAutoPageBreak(true, 20);

// Add border
$pdf->Rect(5, 5, 200, 287, 'D');

// school logo 
$logoPath = '../assets/logoo.png';
if (file_exists($logoPath)) {
    $pdf->Image($logoPath, 10, 10, 25); // (x, y, width)
}

// Header
$pdf->SetFont('Arial', 'B', 18);
$pdf->Cell(0, 10, 'SMART SCHOOL MANAGEMENT SYSTEM', 0, 1, 'C');
$pdf->SetFont('Arial', '', 12);
$pdf->Cell(0, 8, 'Official Payment Receipt', 0, 1, 'C');
$pdf->Ln(10);

// Receipt Info
$pdf->SetFont('Arial', '', 12);
$pdf->Cell(50, 8, 'Receipt No:', 0, 0);
$pdf->Cell(50, 8, $row['receipt_no'], 0, 1);

$pdf->Cell(50, 8, 'Payment Date:', 0, 0);
$pdf->Cell(50, 8, $row['payment_date'], 0, 1);

$pdf->Cell(50, 8, 'Student Name:', 0, 0);
$pdf->Cell(50, 8, $row['student_name'], 0, 1);

$pdf->Cell(50, 8, 'Grade:', 0, 0);
$pdf->Cell(50, 8, $row['grade'], 0, 1);

$pdf->Cell(50, 8, 'Class:', 0, 0);
$pdf->Cell(50, 8, $row['class_id'], 0, 1);
$pdf->Ln(10);

// Divider
$pdf->SetDrawColor(0, 0, 0);
$pdf->Line(10, $pdf->GetY(), 200, $pdf->GetY());
$pdf->Ln(8);

// Payment Details Table
$pdf->SetFont('Arial', 'B', 12);
$pdf->SetFillColor(230, 230, 230);
$pdf->Cell(60, 10, 'Description', 1, 0, 'C', true);
$pdf->Cell(60, 10, 'Amount (LKR)', 1, 0, 'C', true);
$pdf->Cell(60, 10, 'Status', 1, 1, 'C', true);

$pdf->SetFont('Arial', '', 12);
$pdf->Cell(60, 10, 'School Fee Payment', 1, 0, 'C');
$pdf->Cell(60, 10, number_format($row['amount'], 2), 1, 0, 'C');
$pdf->Cell(60, 10, 'Paid', 1, 1, 'C');
$pdf->Ln(15);

// Summary
$pdf->SetFont('Arial', 'B', 12);
$pdf->Cell(50, 8, 'Total Amount Paid:', 0, 0);
$pdf->SetFont('Arial', '', 12);
$pdf->Cell(50, 8, 'LKR ' . number_format($row['amount'], 2), 0, 1);
$pdf->Ln(15);

// Thank You message
$pdf->SetFont('Arial', 'I', 11);
$pdf->MultiCell(0, 8, "Thank you for your payment. Please retain this receipt for your records. For any inquiries, contact the school administration.", 0, 'C');
$pdf->Ln(15);

// // Signature Section
// $pdf->SetFont('Arial', '', 12);
// $pdf->Cell(0, 10, '_________________________', 0, 1, 'R');
// $pdf->Cell(0, 10, 'Authorized Signature', 0, 1, 'R');

// Footer
$pdf->SetY(-30);
$pdf->SetFont('Arial', 'I', 9);
$pdf->Cell(0, 10, 'Generated by Smart School Management System', 0, 0, 'C');

// Output file
$pdf->Output('I', 'Receipt_' . $row['receipt_no'] . '.pdf');
